base_images:
  e2e-test-runner:
    name: redhat-appstudio
    namespace: ci
    tag: e2e-test-runner
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: quay-dast-test-prod-quay-io
  cron: 0 11 * * 5
  steps:
    env:
      QUAY_ENV: STAGE_QUAY_IO
    test:
    - ref: quay-tests-test-quay-dast
zz_generated_metadata:
  branch: main
  org: redhat-appstudio
  repo: rhtap-installer
